### ISSUE TITLE
grow失效

### ISSUE THREAD

**Issue by xiayasky** [chxm1023/Rewrite#2]
使用小火箭，模块已打开，Grow恢复购买失败。![image](https://github.com/chxm1023/Rewrite/assets/44733106/7cddf799-f22a-4abd-b29b-dbd432c7328a)![image](https://github.com/chxm1023/Rewrite/assets/44733106/5ef5882d-6beb-44ce-9c4a-bfb98447daa0)

**Comment by chxm1023** [comment]
这是小火箭的问题，更新脚本后关掉Shadowrocket后台，再重新打开Shadowrocket，然后打开要解锁的APP
